---
- name: vmware
  hosts: localhost
  gather_facts: false
  vars_files:
    - vmware/vars/main.yml
  roles:
    - { role: vmware, tags: vmware }
  tasks:
  - pause:
      seconds: 20

- name: set keys on Linuxes
  hosts: cim, pump, vtsi
  gather_facts: false
  tasks:

- name: ssh keys
  hosts: localhost
  vars:
    - linux_password: generic
  gather_facts: false
  tasks:

  - name: run ssh-copy-id
    command: sshpass -p "{{ linux_password }}" /usr/bin/ssh-copy-id root@"{{ item }}"
    loop:
      - 10.48.77.241
      - 10.48.77.242
      - 10.48.77.243

- name: Change IP on Linuxes
  hosts: cim, pump, vtsi
  serial: 1
  gather_facts: false
  roles:
    - { role: changeip, tags: changeip }

- name: create inventory
  hosts: localhost
  gather_facts: true

  tasks:
    - debug:
        msg: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"

- hosts: temp_group
  gather_facts: false
  tasks:
    - debug:
        msg: "{{ groups['temp_group'] }}"
