---
# tasks file for changeip
- name: copy ipconfigure.sh scripts
  copy:
    src: files/ipconfigure.sh
    dest: /root
    mode: 0750

- name: change ip
  command: /root/ipconfigure.sh
  register: newip

- set_fact:
    ip: "{{ newip.stdout }}"

- debug:
    msg: "{{ ip }}"

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: Wait for SSH to come up
  wait_for: host="{{ ip }}" port=22 delay=20 timeout=320 state=started
  delegate_to: localhost
